server:
  port: 1010

eureka:
  instance:
    hostname: localhost
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
  client:
    # 是否要注册到eureka server中
    fetch-registry: false
    # 是否从其他eureka server中拉去信息
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  # 前端地址
  dashboard:
    path: webui
