server:
  port: 8050

spring:
  application:
    name: config-server
  boot:
    admin:
      client:
        url: http://127.0.0.1:2010
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password: