server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1010/eureka/

spring:
  jpa:
    show-sql: true
  boot:
    admin:
      client:
        url: http://127.0.0.1:2010
  application:
    name: provider-user

logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
