server:
  port: 3015

spring:
  application:
    name: hystrix-turbine
  boot:
    admin:
      client:
        url: http://localhost:2010

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1010/eureka/
  instance:
    prefer-ip-address: true



turbine:
  # 要监控的微服务列表，多个用,分隔
  app-config: consumer-movie,consumer-movie-feign
  cluster-name-expression: "'default'"


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
